Tutorial 12
It just doesn’t work :(

Theres an error on line 78 of the main.js file which is: Uncaught
TypeError: Cannot set property '52' of undefined